= nsa2-libs

== Overview

This module manages all versions of dependencies

== Gradle Version Catalog

=== Required files

- settings.gradle.kts
- libs.versions.toml
- build.gradle.kts

.settings.gradle.kts
[source,kotlin]
----
include::settings.gradle.kts[]
----

.libs.versions.toml
[source,toml]
----
include::libs.versions.toml[]
----

.build.gradle.kts
[source,kotlin]
----
include::build.gradle.kts[]
----

=== Gradle init & wrapper

[source,shellscript]
----
$ gradle init
$ gradle wrapper
----

=== Publish the Version Catalog

[source,shellscript]
----
$ gradlew publish
----

== Using the Published Catalog in Other Projects

- settings.gradle.kts
- build.gradle.kts

.settings.gradle.kts
[source,kotlin]
----
rootProject.name = "nsa2-config"

//enableFeaturePreview("VERSION_CATALOGS")

@Suppress("UnstableApiUsage")
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven {
            url = uri("${artifactory_k8s_contextUrl}")
            credentials {
                username = "${artifactory_k8s_user}"
                password = "${artifactory_k8s_password}"
            }
        }
        mavenCentral()
    }
    versionCatalogs {
        create("libs") {
            from("com.alexamy.nsa2:nsa2-libs:1.0.0-SNAPSHOT")
        }
    }
}
----

NOTE: Please note that mavenCentral() is in repositories section. When repositories is in settings.gradle.kts file, it is not allowed to have repositories in build.gradle.kts file.


.build.gradle.kts
[source,kotlin]
----
//import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

@Suppress("DSL_SCOPE_VIOLATION")
plugins {
    java
// Use the plugin `versions` as declared in the `libs` version catalog
    alias(libs.plugins.spring.boot)
//    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.dependency.management)
}
//plugins {
//    java
//    id("org.springframework.boot") version "3.2.5"
//    id("io.spring.dependency-management") version "1.1.4"
//}

//springBoot { buildInfo() }

group = "com.alexamy.nsa2"
version = "1.0.0-SNAPSHOT"
//java.sourceCompatibility = JavaVersion.VERSION_17
java {
    sourceCompatibility = JavaVersion.VERSION_17
}
//sourceCompatibility = '17'

extra["springCloudVersion"] = "2023.0.1"

// it is not allowed to have repositories in build.gradle file because it is in settings.gradle.kts file.
//repositories {
//    mavenCentral()
//}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter")
    implementation("org.springframework.boot:spring-boot-starter-webflux")
    implementation("org.springframework.cloud:spring-cloud-stream")
//    runtimeOnly("org.postgresql:postgresql")
    runtimeOnly(libs.postgresql)

    // example of using library
    implementation(libs.jasypt)
    // example of using bundle
    implementation(libs.bundles.hazelcast)

    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("io.projectreactor:reactor-test")
    testImplementation("org.springframework.cloud:spring-cloud-stream-test-binder")
}

dependencyManagement {
    imports {
        mavenBom("org.springframework.cloud:spring-cloud-dependencies:${property("springCloudVersion")}")
    }
}

----

NOTE: Also note that if the names include - , when we refer them in our Gradle build scripts, we have to change them to . there. For example, if we definehilt-android , it will become libs.hilt.android when we call it.

=== Resources

- https://medium.com/@joleksiysurovtsev/gradle-version-catalog-simplifying-dependency-management-between-independent-projects-4a8e8dd2cbe0
- https://medium.com/@callmeryan/gradle-version-catalog-728111fa210f
- https://docs.gradle.org/current/userguide/platforms.html

